### ISSUE TITLE
Create Tasks for Backend

### ISSUE THREAD

**Issue by stkiegerl** [FH-Joanneum-Iron-Road-for-Children/iron-road-for-children-backend#14]
**Objective:**
Create all Tasks necessary to run a first version of the backend as container.

**Steps:**
-Create a List of all Tasks
-Add Subtasks
-Add the Tasks to the Backlog

**Deliverables:**
Tasks for the Backend in the Backlog

**Comment by PhilipMoser** [comment]
tasks were created.
