### ISSUE TITLE
[T] Implement "Voting" (formerly "VotingList")

### ISSUE THREAD

**Issue by stkiegerl** [FH-Joanneum-Iron-Road-for-Children/iron-road-for-children-backend#15]
# Description
This task will create the necessary components for the Voting List feature.
The voting list is a summary of the votes of an event.

# Acceptance criteria
- Proper functionality of the Event feature
- DTOs for Create, Delete, and Update are working correctly
- Database entity with Liquibase is created and properly linked
- Handler/service is properly implemented
- Endpoint/controller is properly implemented
- Validators are working correctly

# Dependencies
#17 Implement Event

**Comment by GoldNova** [comment]
Implemented and merged
