### ISSUE TITLE
Setup Development Server

### ISSUE THREAD

**Issue by stkiegerl** [FH-Joanneum-Iron-Road-for-Children/iron-road-for-children-backend#4]
**Objective:**
Set up a Ubuntu Server with basic configurations and required software packages.

**Steps:**
-SetUp Ubuntu 22.04
-Get Public IPv4 & IPv6 address
-SSH Access for all members of the infrastructure team
-Configure Firewall Rules (open port 22, 80, 443 for incoming traffic)

**Deliverables:**
A fully functional Ubuntu Server with basic configurations that is publicly accessable.

**Comment by stkiegerl** [comment]
The Ubuntu Server is now fully functional and publicly accessible at the following IP addresses: 162.55.164.83 and 2a01:4f8:c17:3c0f::/64."

**Comment by stkiegerl** [comment]
The required ports (22, 80, 443) have been opened for incoming traffic in the firewall rules.

**Comment by stkiegerl** [comment]
All members of the infrastructure team have been granted SSH access to the server.

**Comment by PhilipMoser** [comment]
Dev Server is up and running
All members of infrastructur team have been granted SSH access to the server.
