### ISSUE TITLE
Setup Docker

### ISSUE THREAD

**Issue by stkiegerl** [FH-Joanneum-Iron-Road-for-Children/iron-road-for-children-backend#5]
Objective:
Set up Docker on an Ubuntu Server for containerization of applications.

Steps:
-Install Docker Engine
-Verify that Docker Engine is installed and running
-Install Docker Compose
-Verify that Docker Compose is installed and running

Deliverables:
A functional installation of Docker on Ubuntu Server with the ability to run containers and manage them using Docker Compose.

**Comment by stkiegerl** [comment]
Docker Engine has been installed and verified to be running by running an nginx container that can be accessed via the public ip address on port 80. [http://162.55.164.83/](http://162.55.164.83/)

**Comment by PhilipMoser** [comment]
Docker Engine has been installed and verified to be running by running an nginx container that can be accessed via the public ip address on port 80. http://162.55.164.83/
